### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#10]
Need to write down the answer to "why" we are doing this. The early start of the DesignPrinciples.md file tell mostly "what", we need to add "why". Particularly answer why other existing solutions were not chosen.

**Comment by benjchristensen** [comment]
Examples of other options:

- http://blog.wordnik.com/introducing-swaggersocket-a-rest-over-websocket-protocol
- http://jmesnil.net/stomp-websocket/doc/
- http://wamp.ws
- https://thrift.apache.org/docs/concepts
- http://www.grpc.io (https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md)

**Comment by tmontgomery** [comment]
Instead of commenting why individual options are not (well) suited, it would be better to add a Motivation.md file that explains the needs clearly.

For example, why even a protocol at all? Why not just use underlying flow control?

There is a lot of ground covered in a couple issues in the reactive-streams github page over why it is needed on top of TCP. But I'll paraphrase.

Without application feedback in terms of work units done (not bytes), you get into a couple problems:

1. Data is buffered by TCP on the sender and receiver side which means that understanding what is done on the subscriber is not possible.

2. A sender who needs to send a large work unit (larger than the buffering on the TCP sender or receiver sides) is kinda stuck to a bad behaving scenario where the TCP connection will cycle between full and empty and under utilize the buffering drastically (as well as the throughput)

3. TCP isn't the only transport that would make sense to use.

4. TCP handles a single sender/receiver pair and reactive streams allows for multiple senders and/or multiple receivers (somewhat), and

5. (most importantly) decoupling of data reception at the transport layer from application consumption control. I.e. an application may want to artificially slow down or limit processing separately from pulling off the data from the transport.

It all comes down to what TCP is designed to do (not overrun the receiver OS buffer space or network queues) and what reactive-streams flow control is designed to do (allow for push/pull application work unit semantics, additional dissemination models, and application control of when it is ready for more or not). This clear separation of concerns is necessary for any real system to operate efficiently.

This illustrates why ever single solution that doesn't have built in flow control at the application level (pretty much every solution mentioned aside from MQTT, AMQP, & STOMP) is not well suited for usage.

**Comment by benjchristensen** [comment]
We have written https://github.com/ReactiveSocket/reactivesocket/blob/master/Motivations.md which explains the motivations and "why" we are doing this protocol.

**Comment by benjchristensen** [comment]
I want to keep Motivations.md short and concise. If we make it too verbose, it is less likely to be read.

Perhaps though we should have an FAQ for more verbose answers?

**Comment by tmontgomery** [comment]
FAQ would probably be useful.

**Comment by NiteshKant** [comment]
+1 FAQ are good & we can curate them from existing issues too.

**Comment by benjchristensen** [comment]
Some questions to consider:

- Why is cancellation required?
- What are example use cases of cancellation?
- What are example use cases of topic subscription (and push notification)?
- What are example use cases of fire-and-forget versus request-response?
- What are example use cases of request-stream?
- Doesn't binary encoding make debugging harder?
- What tooling exists for debugging the protocol?
- Why are these different flow control approaches needed beyond what the transport layer offers?
- What are example use cases where ReactiveSocket flow control helps?
- How does ReactiveSocket flow control behave?
- How does ReactiveSocket benefit a client-side load balancer in a data center?


Anyone else reading ... what other questions can you think of?

**Comment by stevegury** [comment]
Why is multiplexing more efficient?
Is multiplexing equivalent to pipelining?
What is difference between flow control and the reactive-stream backpressure protocol?
Why is the "TLS False start" strategy useful for establishing a connection?

**Comment by benjchristensen** [comment]
- What are example use cases for payload data on the Setup frame?

**Comment by NiteshKant** [comment]
- Why only 4 interaction models are supported?

**Comment by polarbizzle** [comment]
Why a protocol? What makes creating a new protocol (a quite low level task that most devs don't really do on a daily basis) the right thing for improving large scale distributed systems?

**Comment by polarbizzle** [comment]
I still think that this reads like a shorthand list on a whiteboard for insiders that have been working on it from the beginning rather than communicating motivation clearly to somebody just trying to learn about the protocol for the first time. Why only terse sentence fragment bullet points that aren't laid out with any explanation other than the headings. I wouldn't expect a pulitzer prize winning novel but at least some mention of what pain and inefficiency this is intended to address. You can be concise and write paragraphs I think.

**Comment by benjchristensen** [comment]
@polarbizzle thanks for the feedback, we'll incorporate your questions into the FAQ and consider the use of bullet points vs paragraphs in the Motivations.md file. 

Want to clarify something ....

> (a quite low level task that most devs don't really do on a daily basis)

What is the question behind this statement? Client and server implementations will be provided with the protocol, so only developers wanting to add support to new languages/frameworks will need to worry about the protocol itself.

**Comment by polarbizzle** [comment]
Ah I can see how that'd be confusing. I don't mean that everyone should implement the protocol themselves. I'm just trying to highlight that introducing a new protocol will require tons of marketing. Devs mostly don't think too deeply about the protocols they use. We just use the de facto HTTP, TCP etc . It's true that you don't need everyone to understand the protocol at a super deep detailed level. But you do need people to have an understanding of how it works at a high level and why it's worth trying to learn. That information needs to be easily digested by people who would just use the client / server impls provided for them. If it's not relatively easy to understand what this is and why it's super rad, people won't be convinced and will just write it off as architecture astronaut-iness. I think we should sprinkle the easily digestible stuff everywhere whether it's directly in the document or via links since you never know where people will start reading about the thing and you want to make it as easy as practical for people to make the leap from wtf a new protocol? :unamused:  --> hellz ya lets react to sockets n shit! :rainbow:

**Comment by ReactiveSocketAdmin** [comment]
That is helpful feedback. Do you have time and the interest to help us write such a thing?

**Comment by polarbizzle** [comment]
Yes I'd be happy to help out. I'm not a particularly brilliant writer but I can pitch in for sure.

**Comment by benjchristensen** [comment]
Thank you! We'll be hacking at this stuff today if you want to swing by. Your help will be great to have.

**Comment by wmiaw** [comment]
Please provide definitions for the request frame types in the protocol definition.

**Comment by tmontgomery** [comment]
@wmiaw good point.

**Comment by benjchristensen** [comment]
A blurb to possibly incorporate into the docs:

Today all traffic occurs as synchronous HTTP/1 with text protocols. There are efficiency and performance benefits we can achieve in both server and client by using a multiplexed, binary protocol over a single connection. Additionally, the request/response behavior of HTTP/1, though prevalent, does not efficiently model all desired or required interaction models. For example, use cases best served by push notification are currently achieved through request/response polling, fire-and-forget always receives a response, and streams of data must be collected as a single response, or chunked inefficiently using approaches such as SSE over HTTP/1.

To achieve a multiplexed, single persistent connection, we need to use transport protocols like WebSockets, Aeron, and TCP, which do not provide application level semantics. At most they offer framing. In order to leverage these transport protocols, we need an application protocol.

ReactiveSocket opens up options for applications to use interaction models more appropriate to their use cases while better utilizing the system and network resources for improved throughput and latency.

------

Linked that to:

- https://http2.github.io/faq/#why-is-http2-binary
- https://http2.github.io/faq/#why-is-http2-multiplexed
- https://http2.github.io/faq/#why-just-one-tcp-connection

**Comment by benjchristensen** [comment]
I just posted a major update to Motivations.md. I would appreciate review and feedback from all of you: https://github.com/ReactiveSocket/reactivesocket/blob/master/Motivations.md

**Comment by benjchristensen** [comment]
Motivations.md and FAQ.md have been updated.
