### ISSUE TITLE
Golang client/server implementation

### ISSUE THREAD

**Issue by jakewins** [ReactiveSocket/reactivesocket#107]
First, this looks really, neat; am continuously impressed with the OSS stuff y'all are putting out and was very happy to find someone tackling a reactive stream protocol.

The http://reactivesocket.io/ main page says to ping here for questions around contributions - I'm interested in trying `reactivesocket` for a robotics project, written in Go. As such, I'd need server and client impls in Go, plus transport implementations for websocket and tcp. 

Are you aware of any current efforts to build a Go impl? If not, please let me know if there's anything particular I should consider (like is there a TCK, what licenses are preferred etc); my general plan would be to read through the Java impl and model a Go impl off of how that's structured and tested. 

I figure I'd build it off in my own GH repo, but am happy to donate it back to Netflix OSS later if I get somewhere with it and the code comes out good enough..

All this realizing this is a moving target, which I'm happy with - and conversely, noting that I'm not doing this for a commercially backed project, so I'm making no promises as to whether I'll actually complete it.. :)

**Comment by xytosis** [comment]
Hi @jakewins glad to hear that others are looking to build ReactiveSocket in other languages! I currently don't believe there is a Go impl out there in a public repo. As for things you should consider, I am currently working/almost completed with the TCK, which you can find at https://github.com/ReactiveSocket/reactivesocket-tck (ignore the Quark one in this repo). As for licenses, I think there is a mix of Apache 2 with the Java code and BSD with the CPP.

It would be helpful if your impl did follow the Java one, as I am also working/almost completed with the TCK driver for the Java impl, so that should allow you to test your Go impl in a (hopefully) straightforward way. I'm still fairly new to this project myself, so I'm sure one of the veterans here can comment on things more.

**Comment by jakewins** [comment]
@xytosis sorry for the delay, four weeks of summer hiking got in between :) That's a brilliant set of starting points. My immediate need is for a server impl in Go, so I will start with that, basing the design off of the java one as appropriate and driving it with the TCK.

In the spirit of not leaving unclosable tickets behind, I'll close this ticket again for now, and re-open it when I have something useful to show.

**Comment by xytosis** [comment]
@jakewins sounds good! The TCK and the Java drivers should be complete, and I believe the CPP drivers are being worked on. If you have any questions on the TCK let me know!
