### ISSUE TITLE
feature request: clear request credits

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket#120]
I know this is complicated but want to put it out there for thought.  Is there any nice way to support a clear outstanding request(n) operation.

The awkward thing is timing, as client may clear and then receive a valid response on a stream that the client now believes has 0 credits.  I was thinking of something like a CLEAR_REQUEST frame with optional stream id (single or all streams).  There would probably need to be some some ACK frame in response, so that clients know that server and client are in sync.  Before the ACK is received, the old request credits are assumed to be in place.

The reason for it, is to support situations where flow control changes based on things like mobile connection strength AKA "Pause".  A client may have 200 subscriptions open with generous (>1) requests outstanding on Wifi and want to restrict things when conditions change without cancelling and resubmitting requests.

**Comment by benjchristensen** [comment]
If we pursue something like this, it means we are straying from the Reactive Streams spec. But that's likely okay as network requirements are different. If the application using Reactive Socket is fully Reactive Streams compliant, then it would just never use this behavior. 

By the way, a big reason why this was not done with Reactive Streams is because of the inherent race condition. If the producer is granted 100 credits from the consumer, then the producer is free to deliver them. If the consumer then changes it to 0 while the producer is concurrently preparing and/or emitting the 100, they can't be stopped. 

I don't think that's a reason to not do this, but it does mean that the guarantees from the consumer would instead be "the max the producer can send is the ceiling of whatever has been requested" and then it is a best-effort async race for when the producer updates to whatever the lower value is the client sent. 

Over the network boundaries though, I support pursuing this.

**Comment by benjchristensen** [comment]
Here's another use case where it would be helpful on a network. Imaging a bi-directional channel:

- consumer requests a "live list" of items with request-n == 100
- producer delivers 50 "item adds"
- producer deliver a "done initializing list" metadata message
- consumer now knows it has the initial 50 items for the list and everything going forward are incremental updates
- the consumer at this point may want to reduce it's "request-n" credits to 4 so that the producer pushes incremental updates down slower than the initial burst so that background incremental updates don't overwhelm anything going on in the foreground

This is quite similar to what would be achievable if something like the HTTP/2 WINDOW_UPDATE semantics (at the byte stream level) were exposed to the application APIs and made message oriented (except request-n is cumulative and needs to be reset, whereas WINDOW_UPDATE is explicitly set each time).

**Comment by yschimke** [comment]
I believe consensus is that this complicates the protocol, and makes many things awkward.  We can handle this at the application level.

**Comment by NiteshKant** [comment]
@yschimke update on the wrong issue? I am not really opposed to the idea but may be we need to think about the semantics more.

>> If we pursue something like this, it means we are straying from the Reactive Streams spec.

Correct

>> If the application using Reactive Socket is fully Reactive Streams compliant, then it would just never use this behavior.

@benjchristensen is the thought here that an application can dodge ReactiveStreams in this case and maybe send a special signal (`-1 requestN`) to signal reset?

I was thinking about a slightly different idea of introducing suspend and resume on a stream. The following being a typical interaction:

```
RQ->RS requestN 100
RS->RQ onNext ... 20
RQ->RS suspend 
RS->RQ onNext .... 1 (overflow due to race)
RQ->RS resume
RS->RQ onNext 79                                             
```

The above interaction would ofcourse have buffering on the responder but it will save network data transfer. The responder can then decide to drop and send error if the buffer is too large to handle.
