### ISSUE TITLE
whatwg streams aligned with reactive-streams (conceptually), or why not?

### ISSUE THREAD

**Issue by wenbozhu** [ReactiveSocket/reactivesocket#121]
@tyoshino  

Domenic passed me [this faq link](https://github.com/whatwg/streams/blob/master/FAQ.md#how-do-readable-streams-relate-to-observables-or-eventtarget) a while ago.

**Comment by tyoshino** [comment]
/cc @domenic

Yes, he pointed that FAQ section in response to your question about complexity of the WHATWG Streams, IIRC.

The WHATWG Streams have evolved to answer to various need regarding representation of I/O in the Web. Due to the lock system and byte stream introduced for optimization / transfer offloading, the spec is so big and look complicated, but for comparison with the ReactiveStreams, what I'd like you to look at first are only the following 2 interfaces:
- https://streams.spec.whatwg.org/#rs-class-definition
- https://streams.spec.whatwg.org/#default-reader-class-definition

Please look at the ReadableStreamDefaultReader interface. It represents a mutually exclusive access to a ReadableStream. The releaseLock() method is for releasing it. The other methods could be associated with the ReactiveStreams' concepts like as follows:
- reader.closed promise : Subscriber.onError() and Subscriber.onComplete()
- reader.read() : Subscription.request()
- reader.cancel() : Subscription.cancel()

The difference in how to represent flow control is that the WHATWG reader.read() doesn't take any argument for controlling amount to produce but the queuing strategy passed to the ReadableStream controls whether or not to produce more chunks.

The transform stream, pipeTo() and pipeThrough() (https://streams.spec.whatwg.org/#example-abd17fdb) would correspond to the Processor concept though the construction of the API is very different. The WHATWG Streams represents each data source and data sink as ReadableStream and WritableStream respectively and pipe data between them (possibly with some transformation).

How do the Reactive Streams represent sink of data? Let the API representing a sink of data take a Publisher and have it subscribe to the Publisher to drain data?

**Comment by wenbozhu** [comment]
Thanks Takeshi. 

By "sink of data", you meant write()? Reactive Streams doesn't say much about writes, and Reactive Sockets has something like  .. in [DuplexConnection](void addOutput(Publisher<Frame> o, Completable callback);)
<void addOutput(Publisher<Frame> o, Completable callback);>

@benjchristensen pointed this out for me.  I am yet to figure out the implication to take a publisher instance to send a single frame.

**Comment by benjchristensen** [comment]
If only a single frame is intended for a single Publisher, then typically we have optimizations for that use case since it then by default "caches" that one frame and is pulled whenever the underlying system is ready for it. 

The nature of a system like this is that "vertical" queueing is bounded via the request-n semantics, meaning that any given stream (or request/response) is flow controlled. But the "horizontal" queueing is by default unbounded as typically an application is capable of starting as many streams as they want. That means the queue of streams can grow. 

This is similar to how `flatMap` works which has no constraint on the number of possible streams in flight unless opted into (which ReactiveX supports for example, but can't restrict by default without risk of livelock).

**Comment by benjchristensen** [comment]
> How do the Reactive Streams represent sink of data? Let the API representing a sink of data take a Publisher and have it subscribe to the Publisher to drain data?

Answering this more directly, yes, writing with Reactive Streams is done in the inverse by passing a `Publisher` that will be subscribed to by whatever is doing the actual writing.

**Comment by benjchristensen** [comment]
Here is how a `Publisher` is submitted: https://github.com/ReactiveSocket/reactivesocket-java/blob/4169902707801e87f411ad235f4c137f6ccfb35b/reactivesocket-core/src/main/java/io/reactivesocket/DuplexConnection.java#L29

```java
void addOutput(Publisher<Frame> o, Completable callback);
```

Here is the API for a single Frame: https://github.com/ReactiveSocket/reactivesocket-java/blob/4169902707801e87f411ad235f4c137f6ccfb35b/reactivesocket-core/src/main/java/io/reactivesocket/DuplexConnection.java#L31

```java
    default void addOutput(Frame frame, Completable callback) {
        addOutput(s -> {
            s.onSubscribe(EmptySubscription.INSTANCE);
            s.onNext(frame);
            s.onComplete();
        }, callback);
    }
```

That implementation is not fully compliant with Reactive Streams and should theoretically be changed. It assumes ability to always write a single frame per stream. 

A more correct implementation would be like the optimizations done in RxJava, such as how `ScalarSynchronousObservable` is a marker interface for a stream that is known to contain just a single value. It allows optimizing to just retrieve that single value rather than subscribing, but if passed to code that doesn't know about those optimizations, would still behave correctly with subscriptions (unlike the code I shared above). See here: https://github.com/ReactiveX/RxJava/blob/039a703be5c0bd0c06e21f7c37ab2e1262bb1023/src/main/java/rx/internal/operators/OperatorMerge.java#L243

**Comment by wenbozhu** [comment]
Thanks for the examples. 

Let's close this issue. 

I chatted with the Node developer who works on http/2, today. It's unlikely node will support whatwg streams or give up on the node stream. 

Given RS already works over WS (JS API), the WS over WiSH should make it easier to map RS over http/2 for browsers.
