### ISSUE TITLE
Thoughts on layering (framing)

### ISSUE THREAD

**Issue by wenbozhu** [ReactiveSocket/reactivesocket#122]
> 1) core; 2) resumability etc 3) API semantics 

I felt that 2) and 3) don't have to be layered. They simply offer different properties (including various sub-features for 2 or 3) that are combinatory in runtime as long as both peers support such "capabilities". 

Group-communication protocols (e.g. ISIS based one, [Jgroups](http://jgroups.org/manual4/index.html#protlist)) often follow the same model.

**Comment by benjchristensen** [comment]
A couple weeks ago we had a discussion with @tmontgomery about resumability and whether it should be layered. It got tricky because most forms of resumability benefited from signals into the application tier. This meant that layering became a very leaky abstraction. 

@tmontgomery, I think you're better suited to providing more insight on this one? 

@wenbozhu, what are you suggesting be done?

**Comment by wenbozhu** [comment]
Had a look at the[ #102](https://github.com/ReactiveSocket/reactivesocket/issues/119#issuecomment-255907053)

**Comment by benjchristensen** [comment]
Layering has been formally documented and supported in the browser. 

First, the frame length is called out here: https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#framing It can optionally be provided by the transport and ReactiveSocket be layered on top.

Second, the streamId has been moved to the front (right after the optional length) so that it can also optionally be provided by the transport or another protocol layer. This is shown here: https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#frame-header-format

> Transport protocols that include demultiplexing, such as HTTP/2, MAY omit the Stream ID field if all parties agree. The means of negotiation and agreement is left to the transport protocol.

Is there anything further to do in regards to layering in the spec?

**Comment by benjchristensen** [comment]
Note that these decisions of how to weakly support layering allow implementations to push frame length and streamID into the transport or other layers, but retain comprehensive specification of the protocol such that behavior like resumability, which require understanding of the streams, can work. 

Resumability was a big part of the discussion in how streamId had to be known to the protocol and limited the extent to which we could separate out that knowledge.

**Comment by wenbozhu** [comment]
>  Is there anything further to do in regards to layering in the spec?

Those two changes are sufficient. 

For WiSH (if considered as a transport), we have an action to discuss if in-stream metadata/control-messages (encoding/dispatching) are useful, to be supported below user-level protocols.

I'll open a separate issue to note our conclusion on WiSH, if we decide it's a useful thing to support.
