### ISSUE TITLE
Frame header without length

### ISSUE THREAD

**Issue by abersnaze** [ReactiveSocket/reactivesocket#15]
What does it mean to not include the frame length in the header? Are those 31 bits all zero or is the header 31 bits shorter?

**Comment by abersnaze** [comment]
And while what is bit 0 (R) supposed to mean.

**Comment by NiteshKant** [comment]
Since the fact that frame length is present or not is inferred from the underlying protocol, the frame length can be completely excluded (as opposed to set to 0) for protocols that already support framing. So, the frame header will be 31 bit shorter in such cases.

The [frame encoder code](https://github.com/ReactiveSocket/reactivesocket-java/blob/master/src/main/java/io/reactivesocket/FrameFlyweight.java#L101) does this determination.

**Comment by tmontgomery** [comment]
For efficiency, only 31 bits of the frame length is used. The high order bit is the sign bit for signed types. Java does not support unsigned types and inflating to a long is not necessary. So, it is easiest to simply ignore the sign bit.

**Comment by yunong** [comment]
Should the limitations of Java directly influence the length of this field? Especially since this protocol is runtime and language agnostic.

**Comment by tmontgomery** [comment]
Normally, I would agree.

However, 2GB for a single frame is very large. Practically speaking, it is highly unlikely that even that size of a frame would be a good idea due to head of line blocking. By contrast, HTTP/2 uses a normal size of 24-bits for frame length (with the ability to go higher if needed via settings after init). Same strategy could be employed, but is unnecessary at this stage.

**Comment by benjchristensen** [comment]
I'm considering this one answered. If anyone disagrees with the answer, respond back.
