### ISSUE TITLE
Reserved bits in frame header

### ISSUE THREAD

**Issue by sgudiboina** [ReactiveSocket/reactivesocket#18]
There are only 6 bits of unused flags that can accommodate changes introduced in future versions of this protocol. It will be good to have more "reserved" bits in the frame header (32 extra reserved). Thoughts?

**Comment by stevegury** [comment]
That's a good question.
We never really now how much extra flags we'll need, the current design suppose that we won't heavily rely on those flags. That's why we only reserved for 8 of them.

That being said, if we end up with a lack of flags, we can always reserve the last bit as an indication for more flags present.

**Comment by NiteshKant** [comment]
The negative of reserving extra bits is that it increases the length for every frame, so I would prefer sticking to the current 6 bit space for extra flags and I agree with @stevegury that we should not be relying on these flags much.

**Comment by tmontgomery** [comment]
Remember that the flags are for the protocol operation and what it provides. This is different than the application need for flags, etc. Also, each frame type can have different flags. If a type needs more fields (flags or other fields), it can have them in other places after the Frame Header.

**Comment by benjchristensen** [comment]
Considering this answered. Respond back if more to discuss.
