### ISSUE TITLE
Reduce size of metadata

### ISSUE THREAD

**Issue by fiorix** [ReactiveSocket/reactivesocket#186]
@tmontgomery this is a follow up from #170 to discuss reducing the amount of metadata in frames.

Today the length of metadata is stored in a 24 bit field (0xFFFFFF), which is the same length of the frame length field. Is a 16 bit field (0xFFFF) better suited for this?

**Comment by benjchristensen** [comment]
Since that only gets included if the M flag is set, I don't see the need to save the byte when metadata is wanted.

**Comment by tmontgomery** [comment]
Better would be to prevent fragmentation of metadata. ;)

But my concern is that it would be too restrictive for a lot of apps and that would be a hinderance to adoption. The problem is that metadata in the HTTP world has gotten quite large over time. So, it is natural to consider metadata to be used to emulate that. A hard cap on metadata makes this very difficult and/or possibly stalls usage.

Thus, I think there is not a real practical choice but to allow fragmentation and if that is the case, the size of metadata should be the size of the entire frame itself (i.e. 24-bits).

**Comment by fiorix** [comment]
👍

**Comment by fiorix** [comment]
Fragmentation is hard! :)

**Comment by tmontgomery** [comment]
It brings up very interesting questions. :)
