### ISSUE TITLE
Stream ID reuse

### ISSUE THREAD

**Issue by nickgg** [ReactiveSocket/reactivesocket#221]
I'd like to propose relaxing the restriction on reusing stream ids. With the change from #220 it seems safe to loop back to the beginning of the sequence once the end has been reached, so long as an ID currently in use is not reused.

My motivation is that we have a server-server use case where we expect to run out of IDs in approx. 14 days, and the cost of recreating the millions of active subscriptions is high.

**Comment by stevegury** [comment]
We discussed this in the early days of the design and decided not to allow reuse of the streamId. It was done before the addition of the resumability, and the constraints changed a bit since.

Also, this has been discussed in https://github.com/ReactiveSocket/reactivesocket/issues/59. Right now, the prefered solution is for the server to refuse new streams with `CONNECTION_CLOSE` when it runs out of stream id. This leaves the active streams opened but refuse to create new ones.

**Comment by benjchristensen** [comment]
Something I'm considering on this:

- is it easier for an application to continue creating new streams on a new connection while maintaining existing streams on the previous one?
- or is the complexity of supporting stream reuse low enough to require reuse in all implementations?

It seems that the complexity isn't that big. If a responder receives a request frame and that streamId is unknown to it, it serves the request. If it conflicts with a streamId it still has, it rejects it.

**Comment by benjchristensen** [comment]
Some rules would need to exist, off the top of my head:

- To prevent servers needing to store streamIds for things not needed, like fire-and-forget, or proxies, frame sequences must not overlap when reused. The case I'm thinking about is technically someone could consider using the same streamId for all fire-and-forget requests. But if fragmentation happens that gets messy if they are interleaved. 
- Things are greatly simplified if reuse is only allowed by requests sequentially increasing the ID and needing to wrap the space so they can't just re-use a low number, such as for fire-and-forget
- Responder just rejects if it conflicts with something it already has (applicable to stream and channel which can be long lived)

**Comment by benjchristensen** [comment]
Would this be a problem for proxies which don't want to store state?

I don't think so, because a proxy just blindly forwards whatever it receives. It doesn't care what streams exist as it doesn't store them. 

It would be the eventual responder that would be tracking streamIds still in flight. And since it is connection-oriented, those would all be in a single location. 

Am I missing some use case where a responder would be unable to deal with reuse efficiently?

**Comment by benjchristensen** [comment]
Here is possible wording changes to allow ID re-use: https://github.com/ReactiveSocket/reactivesocket/pull/222

**Comment by tmontgomery** [comment]
I, personally, feel that allowing for reuse is fairly easy from an implementation standpoint and @benjchristensen has pointed out the necessary things to consider.

From a compliant implementation perspective, all Responders would need to assume that re-use will occur and to handle it correctly when it does. So, this is only allowing the Requester to determine if it desires to re-use stream ids.

In that case, maybe it is better to point out that Requesters MAY re-use stream ids and Responders MUST assume stream ids will be re-used.

**Comment by benjchristensen** [comment]
@stevegury Can you take a look at #222 and let me know if you'd be okay with this change?

Also would appreciate input from @NiteshKant and @robertroeser

**Comment by stevegury** [comment]
This looks good to me.

**Comment by NiteshKant** [comment]
This change makes sense to me and yes this suggestion:

>>> Things are greatly simplified if reuse is only allowed by requests sequentially increasing the ID and needing to wrap the space so they can't just re-use a low number

reduces the edge-cases a lot.

The requester implementation for generating IDs will be slightly complex(once wrapped) with a lookup of active IDs map for every new ID. I guess that can be optimized if required.

Food for thought: Since, now IDs can be re-used, do we need the stream ID to be 32 bit long?

**Comment by benjchristensen** [comment]
There are use cases that need more than 65,535 concurrent streams between servers. So we need at least 3 bytes, at which point I'd rather just stick with the 4 we have.

**Comment by benjchristensen** [comment]
Changes to the spec have been merged. Comment again if anything further to discuss here.
