### ISSUE TITLE
Payload frame with neither NEXT nor COMPLETE should be rejected

### ISSUE THREAD

**Issue by lexs** [ReactiveSocket/reactivesocket#226]
The spec currently doesn't mention the behavior if you send a Payload which doesn't set COMPLETE nor NEXT meaning it will effectively be ignored. While this isn't a problem for implementors it might make it harder to talk to a an implementation that doesn't implement the NEXT bit as Payloads will effectively be blackholed.

**Comment by yschimke** [comment]
Also we could tighten up the rules around a next=false, complete=true. Which can't carry metadata etc.  

But I think the immediate answer is to ignore anything that doesn't make sense.

**Comment by benjchristensen** [comment]
Trying to clarify here: https://github.com/ReactiveSocket/reactivesocket/pull/227

**Comment by fiorix** [comment]
I've been thinking if we even need the C flag. Streams could be completed by just not having neither F or N flag.

The rationale to me is this (and sorry if this is a n00b assumption):

REQUEST_RESPONSE: Since 1 response frame is allowed, despite fragmentation, the frame does not need the C flag.

STREAM and CHANNEL: The C flag is redundant here, because frames either have the F or N flag, which are mutually exclusive already. No flag could indicate the completion of the stream.

**Comment by yschimke** [comment]
The protocol already handles the first case

"If a PAYLOAD for a REQUEST_RESPONSE is received that does not have a COMPLETE flag set, the implementation MUST assume it is set and act accordingly."

**Comment by lexs** [comment]
@fiorix If you take N not set as meaning COMPLETE there is no way to do deliver a Payload and also signify the stream is also COMPLETE.

**Comment by fiorix** [comment]
Mmmm, maybe I'm missing something but my understanding is that on a stream you'd set N to indicate there's more frames coming. Not having N could signify the stream is complete. No?

**Comment by benjchristensen** [comment]
N does not mean more frames are coming. A stream can't know that. It means the current frame has data to emit, even if length=0. The PR adds explanation of this. We used to only have C by an edge case exists of an empty payload.

**Comment by fiorix** [comment]
I see, thanks for clarifying.

**Comment by lexs** [comment]
Closing this now as #227 was merged.
