### ISSUE TITLE
How should the server behave if the client doesn't respect the lease?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#25]
Perhaps we should be more clear on what happens if a requestor doesn't respect the lease?

Applicable sections:

- https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#sequences-with-lease
- https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#lease-semantics

It says the responder MUST ignore the request. Are we consciously NOT returning an error message? If so, perhaps we should spell that out (and why)?

The "unexpected" section also isn't clear to me on these two:

> Lack of LEASE frames that stops new Requests is an application concern and SHALL NOT be handled by the protocol.

Does that confirm that the responder will just ignore the requests?

**Comment by tmontgomery** [comment]
The unexpected section comment is about the fact that if a Responder stops sending LEASE messages (and thus prevents a Requester from sending new requests), then that is not handled by the protocol. It's an application concern.

Would like to hear @stevegury on whether an error or ignore is best for when the LEASE is not honored by the Requester. Either is OK, I think. Although, I would have a slight preference that the protocol not try to add specific ERROR returns for that and have the application logic handle it.

**Comment by stevegury** [comment]
Ignoring the request was the easiest thing to do, that's why.

But I forsee a potential problem for a bogus implementation that wouldn't respect the LEASE (don't wait for the LEASE for sending REQUEST) . It could have timing dependent bug where depending on if the server receive a REQUEST before or after it sends the LEASE, the REQUEST would be either ignored or properly handled. This would be relatively hard to debug.

The nicest thing to do (to the protocol implementer) would be to return a SETUP_ERROR(REJECTED_SETUP) with a payload indicating something like "Unrespected lease, eviction notice" before closing the connection.
The other option is to send back an RESPONSE_ERROR for the requests received before the send date of the LEASE. But this would give the oportunity for rogue clients to aggresively NOT respect the LEASE, hoping that the server immediately send a LEASE after a SETUP, and dealing with the case of a few errors.
Ignoring is the simplest thing to do, and it doesn't generate too much load on the server.

That being said, this type of problem will only happen with bogus implementation of the protocol.

I will think a little bit more about that.

**Comment by stevegury** [comment]
To simplify the implementation and avoid having the clients relying on timeout to detect message sent "outside" of a lease, I now believe that responding with an RESPONSE_ERROR is the best thing to do.

c.f. #48 for some motivations.

**Comment by tmontgomery** [comment]
@stevegury you want to update the spec?

**Comment by NiteshKant** [comment]
IMO we should neither prescribe ignore or mandate RESPONSE_ERROR in case when a peer receives a request out of the lease. Following is my reason:

In reality, servers would be keeping a buffer while giving out leases, so most likely a server would be a bit tolerant to handling requests received post expiry. eg: If a server can handle 100 rps, it will give 90 rps leases and hence if there are reasonable amount of out of lease requests, lets say 5, the server can handle it.
Now, if we say the server MUST send an error  for requests received out of lease, then the server is forced to send an error even for requests that it might have otherwise handled, in spite of them being out of lease.

So, instead of saying "An RS MUST send an error response for all requests received out of lease duration" we can say "An RS SHOULD send an error response for all requests received out of lease duration, if it can not handle them"

**Comment by stevegury** [comment]
We talk in person about this with @NiteshKant, he convinced me that the correct phrasing is SHOULD, leaving room for optimization on the server side.

@tmontgomery I'm updating the spec.
