### ISSUE TITLE
Why multiple distinct flow control mechanisms?

### ISSUE THREAD

**Issue by rhs** [ReactiveSocket/reactivesocket#32]
I'm curious why you've chosen to support these two scenarios with two distinct flow control mechanisms rather than one. At first blush they both appear to operate by granting/revoking credit, and while they have slightly different encodings for credit (absolute vs cumulative) and slightly different means for revoking credit (ttl vs cancel), I suspect there is probably a single mechanism that could accommodate both scenarios. This could be important depending on desired topologies, e.g. if you want backpressure to propogate smoothly through a given endpoint then it is important to consider what is involved in order to bridge between different flow control mechanisms.

**Comment by tmontgomery** [comment]
The semantics are actually different. ReactiveStreams has some specific semantics around flow control.

One of them is that ReactiveStreams has no means to revoke credit. Once a request N has been sent, it can't be revoked. Where as with the lease, it must be revokable based on time and also explicitly via a LEASE frame that has number of request set to 0. Both TTL and cancel.

I think keeping them separate is a good idea for other reasons as well. The lease strategy pertains to the entire connection. Where the Response flow control must be based on a stream and only for 2 of the 4 request types (so far). They act different. They will need to be implemented slightly differently. And combining them with the same frame type with conditionals is, IMO, not very clean.

**Comment by benjchristensen** [comment]
I think the key is the difference between flow control for the connection (how many concurrent streams through lease) versus flow control for an individual stream (Reactive Stream `request(n)` semantics).

> if you want backpressure to propogate smoothly through a given endpoint then it is important to consider what is involved in order to bridge between different flow control mechanisms.

This is something we have considered. We strongly want to allow each individual stream to propagate backpressure through application layers supporting Reactive Streams independent of the lease controlling request rates of new streams in each point-to-point relationship. 

If something doesn't support Reactive Streams, then it is an implementation detail of the application layer how to bridge them (such as high/low-level watermarks).

**Comment by wmiaw** [comment]
@benjchristensen pointed out the LEASE is for the number of requests, and not the number of frames. Given that REQUEST N is one request of unbounded frames, what exactly is a LEASE trying to do? It can't be to limit the amount of data sent over the wire within a time frame. It can't be to limit the number of frames that need to be processed at the Reactive Socket protocol layer within a time frame. It also can't bleed into limiting the amount of data or requests the application protocol above needs to process within a time frame since a single Reactive Socket request could contain within its one gigantic payload a million actual application requests.

**Comment by rhs** [comment]
I think an example might help clarify my original question. Say service A is making requests of service B based on events received over a reactive stream from service C. If I understand correctly, then the flow control mechanism in play between service A and B is the lease mechanism and the flow control mechanism in play between A and C is the reactive stream mechanism. The fact that these two have different semantics has implications for A because for A to propagate backpressure it needs to issue requests to C based on leases received from B, however if those leases disappear (or reduce dramatically) then there is no way to reflect that fact back to C because of the mismatch in semantics.

**Comment by NiteshKant** [comment]
>>> Given that REQUEST N is one request of unbounded frames

REQUEST_N is to request N frames and not unbounded. Lease is allowing a "well-behaved" client to send N requests (specified in the lease frame) in the given time period. Where each request is an individual stream. For a request, response frames are flow controlled by REQUEST_N. For REQUEST_CHANNEL, either direction frames are controlled by REQUEST_N.

>>> It also can't bleed into limiting the amount of data or requests the application protocol above needs to process within a time frame since a single Reactive Socket request could contain within its one gigantic payload a million actual application requests.

LEASE semantics are not to guard against abusive clients, if there are a million actual application requests(whatever it means), the client is abusive and servers have to guard against abusive clients by disconnecting connections and not accepting any more connections from the same client.

I agree with the current model of having LEASE and REQUEST_N semantics separated as they are indeed addressing separate concerns of frames in a stream vs requests on a connection.

**Comment by NiteshKant** [comment]
>>> then there is no way to reflect that fact back to C because of the mismatch in semantics.

@rhs I did not understand as to why you say that there is a mismatch in semantics. Of course the way they are communicated are different i.e. different frame types but both flow controls are presenting a number. If I elaborate your example with numbers:

Let us assume that two frames from C constitute one request to B. The requests will look like below:

```
C          <-------                        A                    <-----                         B

                   Request 10                                       Lease 5
```

Since `A` is an intermediary, it should know how to map between requests to `B` and input from `C`. If it does not, then it has to buffer in someway.

The other scenario is that since leases are time based, it may so happen that in between `Request 10` to `C` from `A` and actually receiving data, the leases has expired. This means `A` has to either buffer or drop based on the nature of data. In typical systems where `B` is just a node in a homogeneous cluster of servers, the case that none of the servers in the `B` cluster have any available leases is basically an outage, in which case, it is upto `A` to decide the failure handling i.e. to send an error back to `C` or store and forward later.

**Comment by rhs** [comment]
The missmatch I'm referring to is the second scenario you describe. As you say that there are a range of scenarios where A is forced to buffer because it can't communicate to C what the actual capacity is at B, i.e. it can't propagate certain kinds of backpressure all the way through to C. This means A has to be stateful which can have some significant implications. For example if C is effectively a durable topic (maybe kafka-like or similar), then for C to buffer events at the source is effectively free. In this scenario though, A would need to incorporate its own persistence mechanism to buffer those events caught in between C and B when leases expire.

Another scenario might be if C is a job queue of some sort and A is a scheduling service and B is a compute farm of some kind. If A prefetches jobs from C based on the available capacity at B and this capacity reduces, even though buffering jobs at each instance of A might be easy enough to do, it may result in jobs being stranded on a given instance of A when there is capacity available elsewhere.

**Comment by wmiaw** [comment]
> LEASE semantics are not to guard against abusive clients, if there are a million actual application requests(whatever it means), the client is abusive and servers have to guard against abusive clients by disconnecting connections and not accepting any more connections from the same client.

So what is the point of the LEASE? I still don't have an answer that explains what the point of it is.

Your comment about an abusive client is meaningless IMO because there's nothing that says a client sending one frame of size 2^31-1 bytes asking the server to do 1 million things is against the rules when you are using Reactive Sockets. (Nor should it be against the rules. A protocol that restricts the purpose of the opaque binary data it carries is a bad protocol.) The reason I gave that example is because I still don't know why LEASE was created.

**Comment by stevegury** [comment]
I wrote a tiny explanation of why LEASE are useful in #61

**Comment by wmiaw** [comment]
I got an explanation of LEASE from Todd in person, and I think its purpose will be clarified in the documentation shortly.

**Comment by benjchristensen** [comment]
Clarified in Protocol.md and Motivations.md.
