### ISSUE TITLE
Are the request types too prescriptive?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#40]
The more I think about our current model of defining types of interaction (Fire n forget, Request-Response, Request-Stream, Request-Subscription), it appears to me that we are being too prescriptive. We may finally end up addressing all cases by incrementally adding things like REQUEST_CHANNEL (#30) but the question is, does it belong to the protocol? 

One way to answer this question would be as to what value add does it have. I believe the semantics of what kind of interaction it is, are defined while creating an endpoint and does not change while actually invoking that endpoint. e.g.: An endpoint defined as request and response does not convert to request stream upon invocation. So, is passing this type over the wire meaningful?

Irrespective of whether we define these interaction types, I think there are two important constructs this protocol is establishing today:

- How to multiplex requests (define loosely as a stateful interaction between RQ and RS) over the same connection by attaching the context of the request (request/stream ID) to each data exchange (frame).

- Define how data is exchanged over the wire; by defining the framing semantics for the exchange.

If we instead define the protocol as the above two (eliminating the specific interaction types), the protocol will be more flexible and will not force people to fit their requirements into specific interaction types. The interaction types will be defined by the usage like:

##### Request-Response
```java
reactiveSocket.request() /*Initiate new stream*/
                        .write(request data)
                        .continueWith(response)
                        .take(1)

```
##### Fire and Forget
```java
reactiveSocket.request() /*Initiate new stream*/
                        .write(request data)

```
##### Request-Stream
```java
reactiveSocket.request() /*Initiate new stream*/
                        .write(request data)
                        .continueWith(response)
                        .take(n)

```

##### Request-Subscription
```java
reactiveSocket.request() /*Initiate new stream*/
                        .write(request data)
                        .continueWith(response)

```

##### Request-Channel
```java
reactiveSocket.request() /*Initiate new stream*/
                        .write(request data subject)
                        .continueWith(response)

```

I do believe though that such interaction models are useful while defining client and server libraries, such as developed under reactivesocket-java.

**Comment by benjchristensen** [comment]
Here's how I view it ... if we don't define the interaction models, we end up with just "request channel" semantics and each client/server relationship must then define it's own protocols again on top for what makes up request/response, fireAndForget, etc.

To me it's similar to how I can do anything I want with UDP or TCP - if I define my interaction models and protocol on top of it. 

If we stay too generic we are just another layer. If however we can capture the most common use cases (such as request/response), then any client/server using ReactiveSocket gets that automatically without having to create their own abstractions on top. 

Also, it allows protocol implementations to perform legitimate performance optimizations. For example:

- The protocol has the concept of NEXT_COMPLETE rather than requiring NEXT then COMPLETE as 2 frames as it embraces the concept of request/response, rather than treating request/response as a "stream of 1". This is objectively less bytes on the wire and less processing. I saw a 10-20% throughput improvement by moving from NEXT + COMPLETE to NEXT_COMPLETE and ensuring CANCEL only flows upstream when a terminal event has not already been sent. These are "cheap" actions, but they add up at high throughput.
- FireAndForget is heavily optimized to not send anything back over the wire. This again could not be done if everything was a stream and it was up to the client to ignore the response. The server would always return at least a COMPLETE if FireAndForget was not known.
- RequestStream and RequestSubscription are very similar, but the protocol distinction allows a client to trust that subscription will NOT receive an onComplete and it protects for that. 
- The 4 "request" types currently only receive a single request Frame. This is far simpler for a developer to deal with, whereas Request-Channel will have a stream in both directions. How does a developer know if they are to receive 1 or more? This then becomes a protocol per endpoint that must be established by the application. 

I suggest that we make anything possible by having Request-Channel, but that most use cases will fall under the other 4, and by embracing the interaction models we make it far easier for developers, and allow performance optimizations that would otherwise be impossible, or require custom implementations of protocol handling that bake in application semantics (i.e. knowledge of request/response and fireAndForget).

**Comment by benjchristensen** [comment]
NEXT_COMPLETE usage: https://github.com/ReactiveSocket/reactivesocket-java/blob/05a04089cc4fba01b93185458d545defd26c0fed/src/main/java/io/reactivesocket/internal/Responder.java#L251 compared with a stream (even of 1) sending NEXT and then COMPLETE: https://github.com/ReactiveSocket/reactivesocket-java/blob/05a04089cc4fba01b93185458d545defd26c0fed/src/main/java/io/reactivesocket/internal/Responder.java#L372

FireAndForget sending nothing back over the wire: https://github.com/ReactiveSocket/reactivesocket-java/blob/05a04089cc4fba01b93185458d545defd26c0fed/src/main/java/io/reactivesocket/internal/Responder.java#L438

**Comment by benjchristensen** [comment]
This is quite similar to why RxJava decided to add `Single` alongside `Observable`. Even though everything *can* be achieved with a stream, and `Single` is "just a stream of one", it is a far easier mental model, and performance optimizations can be applied, if behavior is restricted to only allowing a single response. 

See https://github.com/ReactiveX/RxJava/issues/1594#issuecomment-101300655 for reasoning, and details on how much simpler the mental model is for developers.

**Comment by NiteshKant** [comment]
Just to be clear, I am not suggesting that we remove these interaction models from the libraries (protocol implementations). I am suggesting that the protocol creating these abstractions looks redundant as the interaction model is defined by the endpoint and not by an invocation of the endpoint. Sending this information as part of the request means that the model is specified per invocation.

I am aware of the optimizations you mention but I don't think they are tied to the request types. IOW, it is not so that they can only be done by the protocol specifying these interaction models. eg:

If I have an endpoint `/fnf` on the server, the client and server know that it is fire and forget. They have to know it today too out of the band since they have to make/accept an `FNF` request for the endpoint. So, the optimization for the server not sending anything on the wire can still exist when the server chooses to do so.

NEXT_COMPLETE: I think it makes sense to keep NEXT_COMPLETE irrespective of whether we have these well defined interactions models or not.

The reason why I am inclined towards generic nature of the protocol is that it is harder to change protocols but easier to change libraries to support these "ease of use" models.

**Comment by benjchristensen** [comment]
Discussed in person ... we reviewed the experience of implementing reactivesocket-java and how knowledge of interaction models allows performance optimizations. Also, the admittedly subjective choice of what interaction we consider building blocks for all apps using this protocol.

Closing out and retaining the 5 interaction models we've specced.
