### ISSUE TITLE
Optional frame header length before version is problematic

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#45]
Are the first 8 bits your version or the R (which right now has no defined value) followed by a frame length? A frame length that fits within the lower 24 bits also means that the first 8 bits of a frame-lengthed frame will look the exact same as the first 8 bits of a frame-not-lengthed frame, because your initial version is zero.

If you ever want to increment the version in order to support a different frame header field length you won't be able to. But that might be important.

Suggest making the version the very first thing. Magic strings are also sometimes used to differentiate between random bytes and the start of a message, which might be even more important considering you could start reading almost anywhere in the binary stream coming across the wire.

**Comment by tmontgomery** [comment]
This is tricky. Let me explain our thinking.

Framing is actually a layered concern.

For protocols that already have framing, the frame length is not needed. And thus version is the first field after framing. Including the frame length for WebSocket and Aeron (for example), would be a waste of 4 bytes. So, it is optional. Including an optional field after version means adding unnecessary conditional logic. While it would be a predictable branch for a given transport, it does complicate the layout and parsing. Not terribly, though.

Will framing change over time? Very unlikely. But not 0% chance. However, it can still be recovered if needed. Check into how HTTP/2 handles this. It has a frame length prefix as well.

At that point, if frame length layout needs to change, it should be a far more invasive change than simply a new version field, IMO. And should be handled by transport level separation. Ports, resources, etc.

**Comment by wmiaw** [comment]
Framing should not be a layered concern. Sure, you can make your protocol frame smaller by saying you will leverage the underlying protocol's frame to size your frame, but that's dangerous. Because by design the underlying protocol is not required to stay the same for the entire communication nor be visible to the higher layers.

The only requirement you have stated so far is that the underlying protocol is reliable. Well, Ethernet is reliable and has a frame size (that varies in size depending on the driver's configuration) so if you could query the configured frame size you could leave off your length field when constructing the message, and if you could query the frame size when you receive the data you could parse properly. And does this also mean for Ethernet you need to modify your Ethernet frame size every single time you send a Reactive Socket frame? And serialize all of that possibly requiring low-level access to the Ethernet driver?

Also, what about a situation where you have endpoint A on one network X and endpoint B on a second network Y, with X and Y connected through a third network Z? Say X is using Ethernet, Y is using ATM (which has fixed-size frames, so you can't change it to suit your Reactive Socket frame sizes), and Z uses something else completely. You're using Reactive Socket over protocols that provide framing, but you definitely cannot rely upon the underlying protocol framing being used to inform the Reactive Socket stacks of the frame sizes.

The part about the magic string to indicate where a frame starts is to give you a way to recover if a frame gets corrupted and your input buffer position is now at some wrong location and you need to try and drop bytes until you find the start of the next frame.

**Comment by NiteshKant** [comment]
@wmiaw reading your comments on this issue and #44 it appears to me that the confusion arises from the fact that you are assuming that the underlying protocol frame length and ReactiveSocket frame length  has to match. That isn't the case as long as the underlying protocol supports fragmented frames (AFAIK all mature framing protocols do support fragmented frames). Taking an example of an arbitrary protocol `X` that has a max frame length of 100 bytes, in order to send a Reactive Socket frame of 200 bytes, the Reactive Socket frame would be spread over 2 frames of protocol `X`. 

@tmontgomery I think this may be a point worth mentioning in the spec that the underlying protocol must provide reliable and __ordered__ delivery with a capability of frame fragmentation.

**Comment by wmiaw** [comment]
> it appears to me that the confusion arises from the fact that you are assuming that the underlying protocol frame length and ReactiveSocket frame length has to match. That isn't the case as long as the underlying protocol supports fragmented frames (AFAIK all mature framing protocols do support fragmented frames).

I fail to see how this will properly work with the X, Y, Z network scenario I described. You're saying the sender should consider it OK to exclude the frame length if the underlying protocol provides a mechanism by which the frame length can be known. And I'm saying now you have tied your frame to that underlying protocol: the underlying protocol used between sender A and receiver B cannot change nor can it be re-constructed by intermediate points. I can only see this leading to trouble, the same way conflating API and HTTP has caused all sorts of problems.

**Comment by tmontgomery** [comment]
Ethernet is not reliable by the definition in the spec for transport protocols. Loss can occur due to transmission error, and collision, and is not recovered. Also, ATMs behavior means that it is not a direct mapping of frame to ATM cell. I would do that more like how IP maps over ATM cells instead.

So, Ethernet and ATM are not suitable for running ReactiveSocket over. So, the use case you mention of fragmentation across ATM and Ethernet is not how ReactiveSocket has been designed to work.

The only protocols that are supported right now are TCP, WebSocket, and Aeron. It might be better to spell that out in the spec as an exact, inclusive list.

We can add MSL once I understand if it matches the assumptions so far. If not, we can change Reactive Socket so it does.

With those given limits on transport protocol usage, how does your scenario look?

BTW, I am not adverse to always including the frame length. In fact, it pushes the stream ID to be on a 64-bit boundary and avoids the possible alignment mismatch.

**Comment by wmiaw** [comment]
I initially filed this question because I didn't know that the sender and receiver had to agree upon the underlying protocol, or that it was a requirement the underlying protocol remains the same and unmolested during communication. Discussion under this and other questions/issues I tells me the design is based on that requirement.

I don't think that is a safe requirement to impose, and always including the frame length removes that requirement as far as I can tell. Alternatively spelling out the requirement that only specific underlying protocols can be used and that the underlying protocol cannot change or have its data be tampered with between the Reactive Socket sender and receiver would also address the question.

**Comment by stevegury** [comment]
I'm not sure to understand what you mean by
> a requirement the underlying protocol remains the same and unmolested during communication
Could you elaborate with an example?

**Comment by NiteshKant** [comment]
Issue #44 has discussions and examples around this point.

**Comment by benjchristensen** [comment]
We have clarified the spec to specify when LENGTH is required, and when it is not required. It MUST exist on TCP, and MUST NOT exist on Aeron and WebSockets. No other transport protocols are officially supported at this time.

Version is now part of SETUP. ReactiveSocket is connection oriented, so it is the SETUP of a connection that defines the version for the life of the connection.
