### ISSUE TITLE
Flags appearing before frame type requires reverse parsing

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#46]
Currently flags appear in the 8 bits between VERSION and FRAME TYPE in the frame header. I thought at first this means flags should be identified by the version. This is further supported by the idea there is an I flag to ignore the frame (type) if not understood, but the M flag is per-frame type, and the remaining 6 bits are flags available for a frame type to define.

Why are you placing flags before the frame type? Are you trying to align things on 16-bit boundaries? If so, why? I don't think you need to unless you are trying to match this to some underlying protocol or link layer.

(The I flag appears to be pointless—if the receiver can't understand a frame then of course it has to ignore it.)

**Comment by tmontgomery** [comment]
Typical use of version is that everything after the version field can vary based on the version. So, all fields are up for grabs.

The currently defined and specified version statically defined the Flags (which are actually all per type), Type, StreamId, and each type layout. So, the ordering of all fields after Version depends only on version. Thus all flags are per type with some being re-used for convenience between types. This is not unusual in protocols that use a type field to determine various layouts.

Type should be accessed on a 16-bit boundary, yes. While this is an optimization, there is no downside to doing this and can be a slight upside when frames are aligned to field boundaries as the type field is accessed frequently.

The I flag is for extension. There may be added frame types that if not understood mean the connection should be terminated.

**Comment by wmiaw** [comment]
The flags are currently defined by frame type, not by version. There is nothing that stops bit 3 from meaning HAWAII for a ALOHA frame type but bit 3 meaning COME_GET_SOME for a DOOM frame type.

If the 8 bits can only mean specific flags independent of the frame type, then they should all be listed and defined in the header definition and only indicated if they matter or not in each frame definition.

If it really is that the flag bits can differ by frame type, then they should appear after the frame type otherwise a streaming parser has to "parse backwards".

The I flag is currently defined as "ignore frame if not understood", not "terminate the connection if not understood". And there is no terminate connection defined in the protocol. Unless you mean terminate the underlying protocol connection, which I think you do from reading the rest of the definition but also doesn't necessarily mean anything unless you also add a restriction that the underlying protocol must have the concept of establishing and terminating communication channels. You do not currently place that restriction on the underlying protocol.

**Comment by NiteshKant** [comment]
>>> If it really is that the flag bits can differ by frame type, then they should appear after the frame type otherwise a streaming parser has to "parse backwards".

A streaming parser that parses a bit at a time would, may be. Parsers usually would parse the "data" in a streaming fashion and not really frame headers which are strictly bit aligned, as here. For the systems we are talking about, It would be ok to buffer 8 bytes for example to understand the frame layout completely. So, I do not see any problem here.

>>> The I flag is currently defined as "ignore frame if not understood", not "terminate the connection if not understood".

What it means is that if the bit is set then ignore, if not then don't ignore, which would mean take an action as you deem necessary; ignore request, send error, close connection, whatever the application desires. I am not sure we should be prescriptive here of what "don't ignore" means. OTOH, having the ignore flag is handy to tag really ignorable flags otherwise it is non-deterministic as to what a receiver should do with a frame it does not understand without breaking the requesters expectations.

**Comment by stevegury** [comment]
I think @NiteshKant properly address the question about the `I` flag.

Regarding the order of flags vs version, I thin that in practive it doesn't really matter, but theoritically you're right and it makes sense to reverse the order.
Unless I'm missing something, I don't think it should be a big problem on our side to make it happen.

**Comment by tmontgomery** [comment]
Having seen how FPGAs/ASICs typically parse and designed protocols for better implementations in hardware, the order of bits is not a problem for __this__ frame header size here in terms of the access pattern.  Nor for cache striding if flags and type were crossing cachelines. Having conditional bits based on frame type preceeding it is only an aesthetic and field alignment choice. 

To the field alignment end, moving the 16-bit frame type to right after version will mandate it is accessed off boundary. Which on each frame is/would be a perf hit (and I'm not entirely happy with stream Id being off boundary anyway, but it isn't accessed as much as type is). Minimal, but still not ideal. How big? Would only really matter for pure IPC use cases. Aeron would notice it, but that is about it. But we are not burning frame types quickly, so that can be mitigated by reducing the frame type field to 8-bits.

Something like:

```
     0                   1                   2                   3
     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |R|                 Frame Length (for TCP only)                 |
    +---------------+---------------+-------------------------------+
    |    Version    | Frame Type    |I|M|  Per Type Flag            |
    +---------------+---------------+-------------------------------+
    |                           Stream ID                           |
    |                                                               |
    +---------------------------------------------------------------+
                           Depends on Frame Type
```

This keeps `I` and `M` as used by all frames and leaves a ton of space for more flags that are type dependent.

Thoughts?

**Comment by wmiaw** [comment]
Makes sense to me. But maybe from the previous comment the flags should be defined by version rather than frame type. Both approaches make sense to me.

**Comment by tmontgomery** [comment]
I would be concerned that flags being only dependent on version would burn/use-up the bits a little too much for only 8-bits. As all flags would have to be accounted for up front.

**Comment by wmiaw** [comment]
I agree that it is better for the flags to be defined by the frame, rather than the version.

**Comment by tmontgomery** [comment]
After discussion, we landed on removing version and swapping frame type and flags.
