### ISSUE TITLE
Fragment is undefined

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#51]
Fragments are referred to in a few places. From the frame definitions I am led to believe that a fragment is another frame (e.g. two response frames, the first with F-flag set, the second with C-flag set). But the term fragment is not defined. Is a fragment just another frame? Then it should just say frame.

**Comment by NiteshKant** [comment]
Fragmentation and reassembly is defined in [this section](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#fragmentation-and-reassembly)

>>> (e.g. two response frames, the first with F-flag set, the second with C-flag set)

No, for a frame fragmented into two frames, the first will have `F` flag set and the second will not have this flag set. Since, the underlying protocol is ordered, the presence of `F` flag in the first frame and absence in the second determines that the single frame is spread into two frames.  `C` flag denotes completion of the response. It is an optimization to avoid sending an independent COMPLETE frame, when possible.

**Comment by wmiaw** [comment]
Fragments should be defined at the top in terminology. Or when it is first referenced. Not at the bottom after it is already used in a bunch of places.

I don't understand your sentence about fragmenting a frame into two frames. Do you mean fragmenting an application's metadata and payload data into two frames?

Also not understanding what you say by an optimization to avoid sending an independent COMPLETE frame (which I assume to mean a RESPONSE frame with the C flag). If a RESPONSE frame contains an F flag, then another RESPONSE frame must be after it. If a RESPONSE frame contains a C flag, then that is the final RESPONSE frame. C and F flags are mutually exclusive. If all of the application data is provided in a single RESPONSE frame than that one frame should have the C flag set.
    Is my understanding wrong?

**Comment by NiteshKant** [comment]
You are correct that C and F flags are mutually exclusive, I mentioned C as it appeared from your comment that C was intended to be used as fragment completion. 

Fragmentation here is for the case if the data/metadata is too big to fit into a single Reactive Socket frame (the max frame length is bounded), then it can be transmitted as multiple Reactive Socket frames. It is not equivalent to two response frames as the recipient can not handle it independently (not a well formed JSON when split into two frames for example) as is the case with two RESPONSE frames.  It is analogous to [HTTP/2 continuation frame](https://http2.github.io/http2-spec/#CONTINUATION)

**Comment by tmontgomery** [comment]
Some clarifying language added.
