### ISSUE TITLE
Coupling SETUP / SETUP ERROR to underlying protocol is problematic

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#56]
In "Handling the Unexpected" the following rules are stated:
> A server MUST ignore a SETUP frame after it has accepted a previous SETUP.
> A client MUST ignore a SETUP_ERROR after it has completed connection establishment.

This clearly only works if the connection establishment described under "Connection Establishment" is based on the lower-level protocol connection, because there is no "Connection Close/Reset" defined. And again it requires the Reactive Socket protocol to depend and interact with the underlying protocol.

Otherwise, a client may think it needs to establish a new Reactive Socket connection for whatever reason, but it cannot because the server is still receiving frames from the same "place" on its side. And therefore all communication is now dead and cannot recover.

**Comment by tmontgomery** [comment]
Logically, I don't see how this follows. Can you clearly explain the sequence of frames you are worried about?

**Comment by wmiaw** [comment]
RQ -> RS: SETUP + L
RS -> RQ: LEASE
... <communication proceeds>
RQ loses network connectivity or times out or whatever, and thinks the connection to RS is lost.
The connection RS associates with RS is via a proxy or something and therefore still open.
RQ wants to open a new Reactive Socket channel to RS:
RQ -> RS: SETUP + L
RS rejects this SETUP because it already got a SETUP on this "connection"

**Comment by tmontgomery** [comment]
The proxy case is the most awkward as it involves at least 2 transport protocol instances (instead of 1).
The assumption has been that if ReactiveSocket determines the connection is dead, that it teardown itself __and__ the transport connection and start again afresh. For a proxy, not sure if it might make more sense to teardown both connections if one dies or has to be re-instantiated due to EOF/RST/etc. I may not fully grok the proxy use cases, though.

KEEPALIVE is/was the intended mechanism to detect a "dead" connection like this. In this case, the protocol can not make progress. KEEPALIVEs should be flowing __AFTER__ connection establishment completes. That needs to be made clear. Without KEEPALIVEs flowing (even if it can't be sent yet due to connection establishment state), the connection is essentially unusable and should be torn down and rebuilt.

Having thought of this more, though. You are correct. SETUP + L needs a timeout. Probably different than KEEPALIVE, I think. Re-establishing ReactiveSocket with a coordinated disconnect and reconnect seems so heavy-weight and counter to what we have been discussing.

**Comment by benjchristensen** [comment]
We have considered this and decided nothing in the protocol needs to change. Either client or server would determine the connection is no longer valid and would tear down.
