### ISSUE TITLE
Stream Prioritization

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#57]
Should we include stream prioritization?

Example from HTTP/2 https://http2.github.io/http2-spec/#StreamPriority

**Comment by stevegury** [comment]
This is pretty difficult to implement correctly (especially if we want to dynamically change the priority).
We can leave room for it in the protocol but I would rather focus on something more simple as a starting point.

**Comment by NiteshKant** [comment]
I agree with @stevegury that stream priorities are very complex and I think they have limited usefulness. In the scenario where multiple disparate requests are using the same connection, the concept of priority becomes vague as one can not correctly define a priority without knowing the other requests that can go on that connection. I would stay away from them unless we have a usecase which can not be addressed otherwise.

**Comment by tmontgomery** [comment]
A Requester could add stream priority to the metadata of the request to help give priority to certain requests for scheduling. Don't think it needs to be a ReactiveSocket field directly.
