### ISSUE TITLE
Lease Semantic/Contract

### ISSUE THREAD

**Issue by yunong** [ReactiveSocket/reactivesocket#61]
Is there a document that elaborates on the Lease mechanism? I see it referred to quite a bit in the protocol document, and the "lease contract" is even mentioned. However I don't see any concrete details on the motivation and explanation of what the lease actually is.

To put it bluntly -- what's the point of having a lease?

**Comment by stevegury** [comment]
The LEASE contract is the mechanism used by the server to control the flow of requests from the client.
A server can use this technique to drain its clients before a shutdown, or it could reduce the rate of the requests it receives because it is detecting some queueing on its side...

One interesting feature of the LEASE mechanism is that it is explicit, if a client doesn't have a LEASE it can't send a request. So an overloaded server doesn't have to do any action to reduce its load (implicitly).

**Comment by tmontgomery** [comment]
The details of how LEASE is generated, determined, etc. is best left to a separate doc. The mechanics from the protocol operation are in the spec currently.

**Comment by wmiaw** [comment]
I got an explanation on the purpose of LEASE speaking with Todd directly. I think the purpose of LEASE will be clarified in the documentation by Todd moving forward.
